### ISSUE TITLE
Roadmap 2

### ISSUE THREAD

**Issue by lucacasonato** [denoland/vscode_deno#194]
Now that most burning fires have been put out #121 can be closed and it is time for a new roadmap. The goals for the next few weeks and months should be stabilizing the extension, improving compatibility with mixed Node + Deno projects, and making the extension more easy to use. Here are some ideas in rough order of priority (top is most important):

- [x] `editor.defaultFormatter` should not be hijacked by `deno fmt`
- [ ] ~Implement `"deno.include"` setting to enable the extension on files matching this path.~ not possible until `deno lsp`
- [ ] ~Implement `"deno.exclude"` setting to disable the extension on files matching this path.~ not possible until `deno lsp`
- [ ] Various improvements to language server. (#187)
- [x] Add Deno debugging configuration.
- [x] Re-add `Enable Deno` and `Disable Deno` commands to quickly switch `"deno.enable"` in `.vscode/settings.json`. (#170)
    - This was instead covered by `Init` command.
- [ ] Support re-exports from files like `deps.ts` for autocomplete.
- [ ] Support configuration in workspace and user settings, not just project settings.

And various high priority bugs that need to be fixed:
- [ ] Syntax highlighting is somewhat broken (#150)
- [ ] `@deno-types` does not work on first load (#97)

---

The future goal is still to integrate LSP into the `deno` binary.

**Comment by brandonkal** [comment]
Nice. Also
#124
#113
are still bugs.
-1 on a toggle command. There are many existing generic settings toggle solutions so no need to reimplement the wheel there.

I'd also love a deno.enable auto where a file is recognized as Deno if it contains the string "Deno" (either as namespace usage or in a comment).

**Comment by CGQAQ** [comment]
@lucacasonato Please create an issue for each item in the checklist, so I can reference in pr

**Comment by callionica** [comment]
If console.log isn't writing to the VS Code debugger output pane, it's hard to see the VS Code integration as working, so it'd be great to get the fix to Deno #4502

https://github.com/denoland/deno/issues/4502

Maybe this is covered by the debugging item?

**Comment by nayeemrmn** [comment]
@callionica That's independent of VSCode integration, since the same issue will occur with Chrome devtools for instance.

**Comment by callionica** [comment]
@nayeemrmn Yeah, I recognise that it's under a different repo. I hope this roadmap is being used to show the path to completing specific customer scenarios and fulfilling user expectations. That's a good way to prioritise where to put your resources.

My point is that a basic user expectation of being able to write Deno code in VS Code is that you can step debug with output going to the integrated debugger window. Currently that user expectation is not being met. And it's such a core part of the experience that meeting that expectation should be prioritised and resourced along with these other features.

Sometimes roadmaps will show dependencies on other teams/feature areas. For me, that's a necessary part of prioritisation and communication.

**Comment by jsejcksn** [comment]
> Re-add `Enable Deno` and `Disable Deno` commands to quickly switch `"deno.enable"` in `.vscode/settings.json`

Being tracked in #170 if you want to add that to the description

**Comment by CGQAQ** [comment]
@lucacasonato First one should be checked due to #193 closed, in fact, fmt is not been hijacked at all.

**Comment by jeiea** [comment]
https://github.com/denoland/deno/issues/8400
It seems `deno lsp` is implemented. Is there any blocker still left?

**Comment by lucacasonato** [comment]
@jeiea Yes, the LSP is still not at feature parity with current extension. Only once that is the case will we switch.

**Comment by lucacasonato** [comment]
We now use `deno lsp` in version 3.x of the extension. The roadmap issue for lsp is https://github.com/denoland/deno/issues/8643. Closing this issue.
