### ISSUE TITLE
Roadmap 3.0

### ISSUE THREAD

**Issue by kitsonk** [denoland/vscode_deno#348]
With the release of 3.0 version of the extension, there was a significant re-write leveraging the LSP server built into the Deno CLI.  We focused on making the initial release of the v3.0 extension as an "MVP" but there are certain features that we need to add/restore/rebuild as well as improvements overall to the extension.

There are quite a lot of features that are either fully provided by a LSP server, or require significant work there to enable them in the extension.  There is an existing issue in the Deno CLI to track those: https://github.com/denoland/deno/issues/8643

Here is a list of functionality that we want to add to the extension.  Those marked with a 🦕  are mostly/fully things that need to occur in the Deno CLI:

- [x] Import auto-completion 🦕 
  - [x] With custom remote registry auto-completion 🦕  
  - [x] Configuration of remote registries
  - [x] A "helper" to configure remote registries
- [x] workspace folders 🦕 
- [x] Debug/Inspector Integration
- [x] `deno test` integration via code lens (#436) 🦕 
- [ ] dependency tree explorer 🦕 
- [ ] refactoring fixes (see: #433) 🦕

**Comment by what1s1ove** [comment]
Hey @kitsonk,
Am I doing something wrong? ☹️

![image](https://user-images.githubusercontent.com/42296182/117703938-ea795200-b1d2-11eb-8e13-0fd99f4f132e.png)

Thanks for all you do!

**Comment by tatemz** [comment]
I see  "workspace folders" is completed but have workspace-folder specific settings been confirmed to be working? I know the docs say each workspace folder must have a `.vscode` folder with the `settings.json` contained in it, but the VS Code Workspace configuration API supports an alternative setup to use-folder settings. Correct me if I am wrong.

I cannot seem to get the following workspace configuration to properly work:

```json
{
	"settings": {
		"deno.enable": false,
		"deno.lint": true,
		"deno.unstable": true,
		"deno.codeLens.implementations": true,
		"deno.codeLens.references": true,
		"deno.suggest.autoImports": true,
		"deno.suggest.completeFunctionCalls": true,
		"deno.suggest.names": true,
		"deno.suggest.paths": true,
		"deno.codeLens.referencesAllFunctions": true,
	},
	"folders": [
		{
			"name": "My Python Folder",
			"path": "./my-python-folder"
		},
		{
			"name": "My Deno Folder",
			"path": "./my-deno-folder,
			"settings": {
				"deno.enable": true,
				"deno.importMap": "${workspaceFolder}/import_map.json"
			}
		},
	]
}

```

**Comment by kitsonk** [comment]
@tatemz sorry, it was pulled from 1.10.0 because of a late breaking issue and needs to be re-landed.  The extension side is all ready to go.

**Comment by kitsonk** [comment]
This issue has reached the end of its usefulness, so I am going to close.

I opened #470 and #433 was already opened.

The extension and the language server are tightly coupled together, you can see the current roadmap for the language server as part of the roadmap for the CLI (see: https://github.com/denoland/deno/issues/11168).
