### ISSUE TITLE
1.0

### ISSUE THREAD

**Issue by justjavac** [denoland/vscode_deno#4]
vscode extension for Deno has a new repository now 🎉, so we should start from scratch(0.x), and publish a usable version when Deno 1.0 is released.

- [x] use github actions #2
- [x] publish 0.x on VS Code Marketplace
- [x] mark original extension as deprecated and redirect to the official extension justjavac/vscode-deno#76 
- [ ] use github actions to auto publish
- [x] use LSP #5 
- [x] import maps
- [x] webworker #9
- [ ] auto(or manual) `deno cache` when importing a module that has not been cached
- [x] provides `deno fmt` as a formatter #10
- [ ] provide autocomplete for std modules when type 'import ... from "'
- [x] when `package.json` is detected in the root directory, display a prompt "disable Deno extension or not".(_I've received a lot of feedback that this extension will break non Deno projects when it's enabled._) #7
- [x] support `@deno_types` #21
- [ ] debug

beyond 1.0

- force use of Deno's built-in version of typescript(current we use of VSCode's built-in version)
- coexist deno and node in the same project

future

- rewrite LSP's server side with Deno itself [need discuss]

**Comment by gewoonwoutje** [comment]
Will this new 1.0 version be published under the publisher 'denoland'?

**Comment by justjavac** [comment]
when this extension is stabilized, there are still many bugs to be solved

**Comment by David-Else** [comment]
The official `denoland` extension is on the marketplace now! https://marketplace.visualstudio.com/items?itemName=denoland.vscode-deno

**Comment by lucacasonato** [comment]
Closing in favor of #121
